//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareApproach.TestingExtensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareApproach.TestingExtensions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual:&lt;{0}&gt;. Expected To contain&lt;{1}&gt;..
        /// </summary>
        internal static string ActualExpectedContainString {
            get {
                return ResourceManager.GetString("ActualExpectedContainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual:&lt;{0}&gt;. Expected&lt;{1} to {2}&gt;..
        /// </summary>
        internal static string ActualExpectedRangeString {
            get {
                return ResourceManager.GetString("ActualExpectedRangeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual:&lt;{0}&gt;. Expected&lt;{1}&gt;..
        /// </summary>
        internal static string ActualExpectedString {
            get {
                return ResourceManager.GetString("ActualExpectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual:&lt;{0}&gt;..
        /// </summary>
        internal static string ActualString {
            get {
                return ResourceManager.GetString("ActualString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lowerInclusive must be less than the upperInclusive..
        /// </summary>
        internal static string ArgumentOutOfRangeExceptionLowerNotLessThanUpperMessage {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeExceptionLowerNotLessThanUpperMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; is assignable from &lt;{1}&gt;..
        /// </summary>
        internal static string AssignableFromString {
            get {
                return ResourceManager.GetString("AssignableFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong exception was thrown. Actual:&lt;{0}&gt;. Expected&lt;{1}&gt;..
        /// </summary>
        internal static string ExceptionActualExpectedString {
            get {
                return ResourceManager.GetString("ExceptionActualExpectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exception was thrown.  Expected&lt;(0)&gt;..
        /// </summary>
        internal static string ExceptionNoneThrownString {
            get {
                return ResourceManager.GetString("ExceptionNoneThrownString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; is not assignable from &lt;{1}&gt;..
        /// </summary>
        internal static string NotAssignableFromString {
            get {
                return ResourceManager.GetString("NotAssignableFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        internal static string NullString {
            get {
                return ResourceManager.GetString("NullString", resourceCulture);
            }
        }
    }
}
